### ISSUE TITLE
完善 makefile 和 docker

### ISSUE THREAD

**Issue by Liu233w** [Liu233w/acm-statistics#369]
- [x] 添加 `make help` 并将其作为 make 的默认选项
- [x] 完善 `README.md` 的文档
- [x] 给 docker compose 添加自动更新镜像的功能
  - 包括镜像和 docker-compose 配置文件
- [x] 想一个使用 dev 模式开发前端的方法
  - 当前直接部署的形式没法使用 hot reload，在容器外运行前端时不方便访问其他容器的数据；把源代码 mount 进去的时候没法自动监控代码改变。
